on: 
  push:
  workflow_dispatch:
jobs:
  Cloudformations-Deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of git code
        uses: actions/checkout@v4.1.7
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - shell: pwsh
        run: Install-Module -Name AWS.Tools.CloudFormation --force
